import fs from "node:fs";
import path from "node:path";
import prompts from "prompts";
import { readDesignData } from "../lib/design";
import { readProjectData, requireProjectDir, slugify, writeProjectData } from "../lib/project";
import { BACKGROUND_QUESTION, BEAT_STRUCTURE_QUESTION, FONT_QUESTION, HOOK_STYLE_CHOICES } from "../lib/template-questions";

export async function templateCommand(slug: string): Promise<void> {
  requireProjectDir(slug);
  const project = readProjectData(slug);
  const design = readDesignData(slug);

  // Template decisions need a real locked example to preview against, not
  // an abstract choice -- same reasoning as doing this after content
  // structure, not before.
  const hasAnyContentStructure = design?.phases?.some((phase) =>
    phase.topics?.some((topic) => (topic.contentStructures?.length ?? 0) > 0)
  );
  if (!hasAnyContentStructure) {
    console.error(
      `\nNo content structure found for ${slug} -- run \`cutshort design content-structure ${slug}\` first. ` +
        `Template decisions need a real locked example to preview against.`
    );
    process.exit(1);
  }

  if (project.template) {
    const { keep } = await prompts({
      type: "confirm",
      name: "keep",
      message: `Already using template "${project.template}" -- keep it?`,
      initial: true,
    });
    if (keep) {
      console.log(`\nStill using "${project.template}".\n`);
      return;
    }
  }

  const { choice } = await prompts({
    type: "select",
    name: "choice",
    message: "Use the default template, or create a new one?",
    choices: [
      { title: "Default (src/templates/default/)", value: "default" },
      { title: "Create a new one", value: "new" },
    ],
  });

  if (choice === "default") {
    project.template = "default";
    writeProjectData(slug, project);
    console.log(`\nUsing src/templates/default/.`);
    console.log(`\nNext: run \`npm run cutshort -- scan ${slug}\`\n`);
    return;
  }

  if (choice === "new") {
    console.log("\nDesigning a new template -- structural/visual questions only (copy is `design`'s job).\n");

    const answers = await prompts(
      [
        { type: "text", name: "templateName", message: "What should this template be called?" },
        { type: "text", name: "beatStructure", message: BEAT_STRUCTURE_QUESTION },
        { type: "select", name: "hookStyle", message: "How should the HOOK look?", choices: HOOK_STYLE_CHOICES },
        { type: "text", name: "font", message: FONT_QUESTION },
        { type: "text", name: "background", message: BACKGROUND_QUESTION },
        {
          type: "text",
          name: "reuseDecisions",
          message: "Which components (if any) get reused from an existing template vs. built new?",
        },
        { type: "text", name: "otherRules", message: "Any other structural rule this template should follow?" },
      ],
      {
        onCancel: () => {
          console.log("\nCancelled -- no template created.");
          process.exit(1);
        },
      }
    );

    const templateSlug = slugify(answers.templateName);
    const templateDir = path.resolve(process.cwd(), "src", "templates", templateSlug);

    if (fs.existsSync(templateDir)) {
      console.error(`\nA template already exists at src/templates/${templateSlug} -- pick a different name.`);
      process.exit(1);
    }

    fs.mkdirSync(templateDir, { recursive: true });

    const briefLines = [
      `# ${answers.templateName} -- template brief`,
      "",
      "Structural/visual scaffolding captured from `cutshort template`. The actual",
      "component code (theme.ts, the beat components, manifest.ts) still needs to",
      "be built from this brief -- not auto-generated by this command.",
      "",
      "## Beat structure",
      answers.beatStructure,
      "",
      "## Hook style",
      HOOK_STYLE_CHOICES.find((c) => c.value === answers.hookStyle)?.title ?? answers.hookStyle,
      "",
      "## Font",
      answers.font || "_not specified -- default to the shared theme's font_",
      "",
      "## Background treatment",
      answers.background || "_not specified_",
      "",
      "## Reuse decisions",
      answers.reuseDecisions || "_not specified_",
      "",
      "## Other structural rules",
      answers.otherRules || "_none_",
      "",
    ];
    fs.writeFileSync(path.join(templateDir, "brief.md"), briefLines.join("\n"));

    console.log(`\nTemplate brief saved: src/templates/${templateSlug}/brief.md\n`);
    return;
  }

  console.log("\nCancelled -- no template selected.");
  process.exit(1);
}
